# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160608055128 on 2016-06-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('company_recid', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SrService',
            fields=[
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('sr_service_recid', models.IntegerField(primary_key=True, serialize=False)),
                ('company_recid', models.ForeignKey(db_column='company_recid', on_delete=django.db.models.deletion.CASCADE, to='ticket_26758.Company')),
            ],
        ),
    ]
