# -*- coding: utf-8 -*-
# Generated by Django 1.9.6.dev20160425021736 on 2016-04-25 14:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_26333', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedmodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=(-104.9903, 39.7392), srid=4326),
        ),
    ]
