# -*- coding: utf-8 -*-
# Generated by Django 1.9.1.dev20151207200413 on 2015-12-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_25930', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='b',
            field=models.TextField(default=''),
        ),
    ]
