# -*- coding: utf-8 -*-
# Generated by Django 1.9.1.dev20151207200413 on 2015-12-12 22:03
from __future__ import unicode_literals

from django.db import migrations


def test(apps, schema_editor):
    Foo = apps.get_model('ticket_25930', 'Foo')
    print(Foo.objects.filter(a='foo', b='bar'))


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_25930', '0002_foo_a'),
        ('ticket_25930', '0002_foo_b'),
    ]

    operations = [
        migrations.RunPython(test)
    ]
