# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151201231107 on 2015-12-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import ticket_geoff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('objects', ticket_geoff.models.CustomManager()),
            ],
        ),
    ]
