# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151201231107 on 2015-12-02 19:07
from __future__ import unicode_literals

from django.db import migrations
import ticket_geoff.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_geoff', '0002_auto_20151202_1903'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foo',
            managers=[
                ('objects', ticket_geoff.models.AddedCustomManager()),
            ],
        ),
    ]
